name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.18.0'
      - name: Build
        run: ./scripts/build.sh
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/darwin-amd64.tar.gz
            build/freebsd-amd64.tar.gz
            build/linux-amd64.tar.gz
            build/linux-arm64.tar.gz
            build/windows-amd64.zip
